import { useState } from 'react';
import Brand from '../components/Brand';
import { useAuth } from '../context/AuthContext';

export default function AuthPage() {
  const { authenticate } = useAuth(); const [mode, setMode] = useState('login'); const [form, setForm] = useState({ name: '', email: 'demo@contentpilot.ai', password: 'contentpilot' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const update = event => setForm(value => ({ ...value, [event.target.name]: event.target.value }));
  const submit = async event => { event.preventDefault(); setBusy(true); setError(''); try { await authenticate(mode, form); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  const isLogin = mode === 'login';
  return <main className="auth-shell"><section className="auth-side"><div className="auth-brand"><Brand /></div><div className="auth-copy"><div className="eyebrow"><span className="live-dot" />YOUR ALWAYS-ON CONTENT TEAM</div><h1>Turn one idea into <em>everywhere.</em></h1><p>ContentPilot’s AI agents research, plan, and write your next best content — while you focus on creating.</p></div><div className="agent-orbit"><div className="orbit-ring" /><div className="core"><span>✦</span><small>AI TEAM</small></div><span className="agent-chip chip-one">◉ Trend Scout</span><span className="agent-chip chip-two">✦ Script Writer</span><span className="agent-chip chip-three">↗ Platform Pro</span></div><div className="mini-proof"><div className="avatars"><i>J</i><i>M</i><i>S</i><i>R</i></div><span>Trusted by <b>2,000+ creators</b></span></div></section><section className="auth-panel"><div className="auth-card"><div className="mobile-brand"><Brand /></div><div className="auth-heading"><span className="eyebrow">{isLogin ? 'WELCOME BACK' : 'START CREATING SMARTER'}</span><h2>{isLogin ? 'Good to see you.' : 'Create your workspace.'}</h2><p>{isLogin ? 'Sign in to continue building your content engine.' : 'Your first content strategy is just a few clicks away.'}</p></div><form onSubmit={submit}>{!isLogin && <label>Full name<input required name="name" value={form.name} onChange={update} placeholder="e.g. Arjun Sharma" /></label>}<label>Email address<input required type="email" name="email" value={form.email} onChange={update} /></label><label>Password<input required type="password" name="password" value={form.password} onChange={update} minLength="6" /></label>{isLogin && <div className="form-row"><label className="remember"><input type="checkbox" defaultChecked /> Remember me</label><a href="#">Forgot password?</a></div>}{error && <p className="form-error">{error}</p>}<button className="primary-button" disabled={busy}>{busy ? 'Signing you in…' : isLogin ? 'Sign in to ContentPilot' : 'Create free account'} <b>→</b></button></form><div className="divider"><span>or continue with</span></div><button className="google-button" type="button" onClick={() => setError('Google OAuth is ready to connect in the integrations phase.')}>G&nbsp;&nbsp; Google</button><p className="auth-switch">{isLogin ? <>New to ContentPilot? <button onClick={() => { setMode('signup'); setError(''); }}>Create a free account</button></> : <>Already have an account? <button onClick={() => { setMode('login'); setError(''); }}>Sign in</button></>}</p><p className="demo-note">Demo access is prefilled for you.</p></div></section></main>;
}
